name: Build Android Release APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Indique à GitHub d'exécuter toutes les commandes dans le dossier android/
    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Rename APK with Date and Iteration
        run: |
          DATE=$(date +'%d-%m-%Y')
          ITERATION=${{ github.run_number }}
          NEW_NAME="Hush-$DATE-$ITERATION.apk"
          
          mkdir -p output_apk
          cp app/build/outputs/apk/release/app-release-unsigned.apk "output_apk/$NEW_NAME" || cp app/build/outputs/apk/release/app-release.apk "output_apk/$NEW_NAME"
          
          echo "APK renommé en : $NEW_NAME"

      - name: Upload Renamed APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hush-APK-Release
          path: android/output_apk/*.apk
